### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by cwearley** [patiolab/huevo-lang#1]
As someone who was following Hack­ing­Bul­li­pedia and as someone who would greatly benefit from a unified method to record, share, and iterate upon cooking processes, the lack of any progress on the project that won such a forward-thinking contest is greatly disheartening.

Is this language dead or have there been developments that have stalled its release?

**Comment by fgblanch** [comment]
Hi,

The language did progress, but it's been stalled for the latest 8 months. We have some work that will be uploaded to this repository in the following month. Thanks a lot for the support. If you want to keep the conversation please write us to  paco@patiolab.com
